# Generated by Django 2.2.4 on 2019-10-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsV1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondetails',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
