# Generated by Django 2.2.4 on 2019-10-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsV1', '0002_persondetails_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondetails',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='persondetails',
            name='photo',
        ),
    ]
