# Generated by Django 2.2.4 on 2019-10-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsV1', '0004_remove_persondetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetails',
            name='email',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
